tape_deps = [
  dependency('gee-0.8'),
  dependency('gio-2.0'),
  dependency('gstreamer-app-1.0'),
  dependency('gstreamer-1.0'),
  dependency('json-glib-1.0'),
  dependency('libsoup-3.0'),
  dependency('libxml-2.0'),
  dependency('sqlite3'),
  libapi_base_dep,
]

tape_vala_args = [
  '--abi-stability',
  '--hide-internal',
  '--target-glib', '2.76',
  '--vapidir', meson.current_source_dir() / 'lib',
]

tape_sources = files(
  'lib/config.vapi',
  'lib/cachier/cachier.vala',
  'lib/cachier/controller.vala',
  'lib/cachier/humanity-size.vala',
  'lib/cachier/info-db.vala',
  'lib/cachier/location.vala',
  'lib/cachier/storager.vala',
  'lib/player/mods/abstract-mode.vala',
  'lib/player/mods/abstract-shufflable.vala',
  'lib/player/mods/empty.vala',
  'lib/player/mods/flow.vala',
  'lib/player/mods/local.vala',
  'lib/player/mods/track-list.vala',
  'lib/player/gst-player.vala',
  'lib/player/mpris.vala',
  'lib/player/player.vala',
  'lib/ya-m-api/objects/account/about.vala',
  'lib/ya-m-api/objects/additional-info/lyrics-major.vala',
  'lib/ya-m-api/objects/additional-info/lyrics.vala',
  'lib/ya-m-api/objects/additional-info/similar-tracks.vala',
  'lib/ya-m-api/objects/album/album.vala',
  'lib/ya-m-api/objects/album/label.vala',
  'lib/ya-m-api/objects/artist/artist.vala',
  'lib/ya-m-api/objects/artist/counts.vala',
  'lib/ya-m-api/objects/artist/link.vala',
  'lib/ya-m-api/objects/artist/ratings.vala',
  'lib/ya-m-api/objects/collection/collection-tab.vala',
  'lib/ya-m-api/objects/collection/playlist-with-likes.vala',
  'lib/ya-m-api/objects/cover.vala',
  'lib/ya-m-api/objects/download-info.vala',
  'lib/ya-m-api/objects/icon.vala',
  'lib/ya-m-api/objects/landing/in-style.vala',
  'lib/ya-m-api/objects/landing/new-releases.vala',
  'lib/ya-m-api/objects/landing/waves.vala',
  'lib/ya-m-api/objects/library/all-ids.vala',
  'lib/ya-m-api/objects/play.vala',
  'lib/ya-m-api/objects/playlist/case-forms.vala',
  'lib/ya-m-api/objects/playlist/liked-playlist.vala',
  'lib/ya-m-api/objects/playlist/made-for.vala',
  'lib/ya-m-api/objects/playlist/play-counter.vala',
  'lib/ya-m-api/objects/playlist/playlist-absence.vala',
  'lib/ya-m-api/objects/playlist/playlist-recommendations.vala',
  'lib/ya-m-api/objects/playlist/playlist.vala',
  'lib/ya-m-api/objects/playlist/user.vala',
  'lib/ya-m-api/objects/plays.vala',
  'lib/ya-m-api/objects/rotor/block.vala',
  'lib/ya-m-api/objects/rotor/dashboard.vala',
  'lib/ya-m-api/objects/rotor/event.vala',
  'lib/ya-m-api/objects/rotor/feedback.vala',
  'lib/ya-m-api/objects/rotor/id.vala',
  'lib/ya-m-api/objects/rotor/queue.vala',
  'lib/ya-m-api/objects/rotor/restrictions.vala',
  'lib/ya-m-api/objects/rotor/seed.vala',
  'lib/ya-m-api/objects/rotor/sequence.vala',
  'lib/ya-m-api/objects/rotor/session-new.vala',
  'lib/ya-m-api/objects/rotor/settings.vala',
  'lib/ya-m-api/objects/rotor/station-info.vala',
  'lib/ya-m-api/objects/rotor/station-tracks.vala',
  'lib/ya-m-api/objects/rotor/station.vala',
  'lib/ya-m-api/objects/rotor/track-parameters.vala',
  'lib/ya-m-api/objects/rotor/value-heap.vala',
  'lib/ya-m-api/objects/rotor/value.vala',
  'lib/ya-m-api/objects/rotor/wave.vala',
  'lib/ya-m-api/objects/search-result.vala',
  'lib/ya-m-api/objects/track-heap.vala',
  'lib/ya-m-api/objects/track-short.vala',
  'lib/ya-m-api/objects/track/chart.vala',
  'lib/ya-m-api/objects/track/lyrics-info.vala',
  'lib/ya-m-api/objects/track/meta-data.vala',
  'lib/ya-m-api/objects/track/track.vala',
  'lib/ya-m-api/client.vala',
  'lib/ya-m-api/difference-builder.vala',
  'lib/ya-m-api/has-cover.vala',
  'lib/ya-m-api/has-id.vala',
  'lib/ya-m-api/has-tracks.vala',
  'lib/ya-m-api/utils.vala',
  'lib/client.vala',
  'lib/content-handler.vala',
  'lib/enums.vala',
  'lib/hash-store.vala',
  'lib/likes-controller.vala',
  'lib/settings.vala',
  'lib/utils.vala',
  'lib/ya-m-helper.vala',
)

tape_lib = static_library(
  'cassette-tape',
  tape_sources,
  dependencies: tape_deps,
  vala_args: tape_vala_args,
  vala_header: 'tape.h',
  vala_vapi: 'libtape-0.2.vapi',
  vala_gir: 'Tape-0.2.gir',
  link_args: ['-lm'],
  install: false,
)

libtape_dep = declare_dependency(
  link_with: tape_lib,
  include_directories: [
    include_directories('.'),
    include_directories('lib'),
  ],
  dependencies: tape_deps
)

meson.override_dependency('libtape-0.2', libtape_dep)
